name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      OF_BRANCH: master
      OF_ROOT: ${{ github.workspace }}/of

    steps:
      - uses: actions/checkout@v4

      - name: Install extra deps (addon-specific)
        run: sudo apt-get update && sudo apt-get install -y pkg-config

      - name: Clone openFrameworks
        run: git clone --depth=1 --branch=${OF_BRANCH} https://github.com/openframeworks/openFrameworks.git ${OF_ROOT}

      - name: Download oF core libraries
        run: |
          cd ${OF_ROOT}/scripts/linux
          ./download_libs.sh

      - name: Install oF dependencies (official CI script)
        run: |
          cd ${OF_ROOT}/scripts/ci/linux64
          ./install.sh

      - name: Build openFrameworks core (official CI script)
        run: |
          cd ${OF_ROOT}/scripts/ci/linux64
          ./build.sh

      - name: Build example
        run: |
          shopt -s extglob
          mkdir -p ${OF_ROOT}/addons/ofxSocketCAN
          cp -r !($(basename ${OF_ROOT})) ${OF_ROOT}/addons/ofxSocketCAN/
          cd ${OF_ROOT}/addons/ofxSocketCAN/example-socketcan
          make -j$(nproc)