name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        # Cross‑platform build matrix
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # 1. Download openFrameworks
      - name: Setup openFrameworks
        uses: nandenjin/openframeworks-action@v1
        with:
          command: setup-of
          of_version: 0.12.1

      # 2. Checkout the addon (this repo) under apps/
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: 'apps/ofxSocketCAN'

      # 5. Build the example project
      - name: Build example
        uses: nandenjin/openframeworks-action@v1
        with:
          command: build
          project_root: 'apps/ofxSocketCAN/example'
